trigger: none

pool: default
  
stages:
  - stage: tfsecstage
    jobs:
      - job: 
        displayName: tfsecstage
        steps:
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              dir: '$(System.DefaultWorkingDirectory)/env/dev'
  - stage: initplanstage
    jobs:
      - job: 
        displayName: initplanstage
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
              backendServiceArm: 'vikramserviceconnection'
              backendAzureRmOverrideSubscriptionID: '34ba0ff2-f4e0-4102-828e-998d40937cad'
              backendAzureRmResourceGroupName: 'vikramrg'
              backendAzureRmStorageAccountName: 'vikramstorage57909'
              backendAzureRmContainerName: 'vikramcontainer'
              backendAzureRmKey: 'viky.terraform.tfstate'
  - stage: manualvalidationapplystage
    jobs:
      - job: 
        displayName: manualvalidationapplystage
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'vikram'
              allowApproversToApproveTheirOwnRuns: false
              instructions: 'kindly approve'
              onTimeout: 'resume'
  - stage: 
    jobs:
      - job: 
        displayName: apply stage
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
              backendServiceArm: 'vikramserviceconnection'
              backendAzureRmOverrideSubscriptionID: '34ba0ff2-f4e0-4102-828e-998d40937cad'
              backendAzureRmResourceGroupName: 'vikramrg'
              backendAzureRmStorageAccountName: 'vikramstorage57909'
              backendAzureRmContainerName: 'vikramcontainer'
              backendAzureRmKey: 'viky.terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
              environmentServiceNameAzureRM: 'vikramserviceconnection'
              environmentAzureRmOverrideSubscriptionID: '34ba0ff2-f4e0-4102-828e-998d40937cad'
    
